# Generated by Django 4.2.6 on 2023-10-26 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "trabajador_id",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("trabajador_fecha_nacimiento", models.DateField()),
                ("trabajador_tipo_documento", models.CharField(max_length=50)),
                (
                    "trabajador_path_documento",
                    models.CharField(default="PATH/noNe", max_length=255),
                ),
                (
                    "trabajador_nacionalidad",
                    models.CharField(default="No Especificado", max_length=50),
                ),
                (
                    "trabajador_ubigeo",
                    models.CharField(default="No Especificado", max_length=255),
                ),
                (
                    "trabajador_estado_civil",
                    models.CharField(
                        choices=[
                            ("Soltero", "Soltero"),
                            ("Casado", "Casado"),
                            ("Viudo", "Viudo"),
                            ("Divorciado", "Divorciado"),
                            ("Conviviente", "Conviviente"),
                            ("No Especificado", "No Especificado"),
                        ],
                        default="No Especificado",
                        max_length=20,
                    ),
                ),
                (
                    "trabajador_path_doc_estado_civil",
                    models.CharField(default="PATH/noNe", max_length=255),
                ),
                ("trabajador_fecha_ingreso", models.DateField()),
                ("trabajador_fecha_ingreso_sistema", models.DateField()),
                ("trabajador_edad", models.IntegerField()),
                (
                    "trabajador_record",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "trabajador_exp_previa",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "trabajador_total_anios_exp",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "usuario_rol",
                    models.CharField(
                        choices=[
                            ("Administrador", "Administrador"),
                            ("Recursos Humanos", "Recursos Humanos"),
                            ("Trabajador", "Trabajador"),
                            ("Sin acceso", "Sin acceso"),
                        ],
                        default="Sin acceso",
                        max_length=20,
                    ),
                ),
                ("usuario_nombres", models.CharField(max_length=100)),
                ("usuario_apellidos", models.CharField(max_length=100)),
                ("usuario_correo", models.EmailField(max_length=100, unique=True)),
                ("usuario_contrasenia", models.CharField(max_length=50)),
                (
                    "usuario_sexo",
                    models.CharField(
                        choices=[
                            ("Masculino", "Masculino"),
                            ("Femenino", "Femenino"),
                            ("No Especificado", "No Especificado"),
                        ],
                        default="No Especificado",
                        max_length=20,
                    ),
                ),
                ("usuario_telefono", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id_trabajador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="gestion_trabajadores.trabajador",
                    ),
                ),
                ("contrato_tipo", models.CharField(max_length=255)),
                ("contrato_opcion", models.CharField(max_length=255)),
                ("empleo_tipo", models.CharField(max_length=50)),
                ("empleo_situacion", models.CharField(max_length=50)),
                ("empleo_area", models.CharField(max_length=50)),
                ("empleo_proyecto", models.CharField(max_length=50)),
                ("empleo_departamento", models.CharField(max_length=50)),
                ("empleo_cargo", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id_trabajador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="gestion_trabajadores.trabajador",
                    ),
                ),
                (
                    "cuenta_bancaria_codigo_cci",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "cuenta_bancaria_codigo",
                    models.CharField(max_length=255, unique=True),
                ),
                ("cuenta_bancaria_banco", models.CharField(max_length=255)),
                (
                    "cuenta_bancaria_tipo",
                    models.CharField(
                        choices=[("Sueldo", "Sueldo"), ("CTS", "CTS")], max_length=20
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id_trabajador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="gestion_trabajadores.trabajador",
                    ),
                ),
                ("direccion_pais", models.CharField(max_length=255)),
                ("direccion_departamento", models.CharField(max_length=255)),
                ("direccion_provincia", models.CharField(max_length=255)),
                ("direccion_distrito", models.CharField(max_length=255)),
                ("direccion_detalle", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Estudio",
            fields=[
                (
                    "id_trabajador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="gestion_trabajadores.trabajador",
                    ),
                ),
                ("estudio_nivel_educativo", models.CharField(max_length=255)),
                (
                    "estudio_situacion_especial",
                    models.CharField(
                        default="Situación especial no especificada", max_length=255
                    ),
                ),
                (
                    "estudio_regimen_laboral",
                    models.CharField(
                        default="Régimen laboral no especificado", max_length=255
                    ),
                ),
                (
                    "estudio_regimen_laboral_aseguramiento",
                    models.CharField(
                        default="Aseguramiento no especificado", max_length=255
                    ),
                ),
                (
                    "estudio_institucion",
                    models.CharField(
                        default="Institución no especificada", max_length=255
                    ),
                ),
                (
                    "estudio_carrera_educativa",
                    models.CharField(default="Carrera no especificada", max_length=255),
                ),
                (
                    "estudio_capacitacion",
                    models.CharField(
                        default="Capacitación no especificada", max_length=255
                    ),
                ),
                (
                    "estudio_especializacion",
                    models.CharField(
                        default="Especialización no especificada", max_length=255
                    ),
                ),
                (
                    "estudio_id_colegiatura",
                    models.CharField(default="No especificado", max_length=255),
                ),
                ("estudio_fecha_colegiatura", models.DateField(default="1212-12-12")),
                (
                    "estudio_sede_colegiatura",
                    models.CharField(
                        default="Sede colegiatura no especificada", max_length=255
                    ),
                ),
                (
                    "estudio_condicion",
                    models.CharField(
                        choices=[
                            ("Habilitado", "Habilitado"),
                            ("No habilitado", "No habilitado"),
                            ("No especificado", "No especificado"),
                        ],
                        default="No especificado",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sueldo",
            fields=[
                (
                    "id_trabajador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="gestion_trabajadores.trabajador",
                    ),
                ),
                (
                    "sueldo_valor_basico",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "sueldo_asigfam_porcentaje",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "sueldo_asignacion_familiar",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "sueldo_bono_porcentaje",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "sueldo_monto_bono",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "sueldo_mensual",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("sueldo_anual", models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name="trabajador",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_trabajadores.usuario",
            ),
        ),
    ]
